# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [4]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [70]:
print(np.__version__)


1.17.4


#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
np.array([np.nan]*10)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 4. How to find the memory size of any array (★☆☆)

In [75]:
Z = np.array((10, 10))
print(np.size(Z))

# --------------
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

2
100
800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [77]:
help(np.add)

# --------
%run `python -c "import numpy; numpy.info(numpy.add)


       t = op(t, A[i])
 |            r[i] = t
 |        return r
 |      
 |      For example, add.accumulate() is equivalent to np.cumsum().
 |      
 |      For a multi-dimensional array, accumulate is applied along only one
 |      axis (axis zero by default; see Examples below) so repeated use is
 |      necessary if one wants to accumulate over multiple axes.
 |      
 |      Parameters
 |      ----------
 |      array : array_like
 |          The array to act on.
 |      axis : int, optional
 |          The axis along which to apply the accumulation; default is zero.
 |      dtype : data-type code, optional
 |          The data-type used to represent the intermediate results. Defaults
 |          to the data-type of the output array if such is provided, or the
 |          the data-type of the input array if no output array is provided.
 |      out : ndarray, None, or tuple of ndarray and None, optional
 |          A location into which the result is stored. If not provided or `No

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [80]:
Z = np.zeros(10) 
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [22]:
Z = np.arange(10, 50)
Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
Z = np.arange(10)
Z = Z[::-1]
Z

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [117]:
Z = np.array(np.arange(9))
Z = Z.reshape((3,3))
Z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [81]:
Z = np.array([1,2,0,0,4,0])
Z != 0
#----------->
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [21]:
Z = np.eye(3)
Z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [26]:
np.random.randn(3,3,3)

array([[[-0.44181292, -0.73884212,  0.77096027],
        [ 0.12892573,  0.5946318 ,  1.33131127],
        [-0.66883405,  0.83620433, -1.60237067]],

       [[ 0.07173646, -1.18027333,  0.14100094],
        [-0.02434583, -0.74895123, -0.38654738],
        [-0.64525995, -0.74914885,  0.72429823]],

       [[-0.28317592, -0.35451138,  2.34175283],
        [ 0.03751649, -0.75123266, -0.34432712],
        [-1.15930995,  0.34412116, -0.73849446]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [38]:
Z = np.random.randn(10,10)
print(Z.min(), Z.max())

-2.0932190560932122 2.1170385843156194


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [45]:
v = np.random.randn(30)
v.mean()

0.18392819797612645

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [83]:
m = np.ones((3,3))
m[1, 1] = 0
m
#---------->
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [84]:
m = np.ones((3,3))
n = np.zeros((5,5))
n[1:-1, 1:-1] = m
print(n)

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
Z


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [98]:
print(0* np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [85]:
m = np.zeros((5,5))
n = np.eye(4)
m[1:,:-1] = m[1:,:-1]+n*[1,2,3,4]
print(m)

Z = np.diag(1+np.arange(4),k=-1)
Z

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

m#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [28]:
A = np.zeros((4, 8))
B = np.zeros((4, 8))
M = np.array([0,1]*32).reshape(8,8)
idx = np.array()

#m = np.zeros(64)


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [36]:
Z = np.random.randn(6,7,8)
Z[::100]

array([[[-0.04343252,  0.12475789,  0.65302584, -1.02592054,
         -0.11913076, -0.06282628,  0.90281119, -0.36808352],
        [-0.88229078,  0.3443434 , -1.56994283,  0.3749136 ,
         -1.71799384, -0.02189015, -0.45281136,  1.57872928],
        [ 0.74168621,  1.37669066, -0.76521139, -0.20923182,
         -1.35067397,  0.99944698, -0.05194279,  0.29013187],
        [-0.45686745, -0.03888092,  0.02298751,  1.54298403,
         -0.31155748, -1.41905917,  0.72131086, -1.78069069],
        [ 0.12830512, -1.224957  ,  1.27553946, -0.35556475,
         -0.14212259, -0.38046168,  0.60744728, -0.37453615],
        [ 0.14926121, -1.02548685, -0.21218564,  0.23558458,
          1.0103363 ,  0.49678699, -0.38061041,  0.82655648],
        [ 1.09309188, -0.90507013, -1.9628424 ,  0.85421429,
         -1.20918259, -0.3751934 , -0.12134247, -1.34790868]]])

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [87]:
Z = np.random.randn(5,5)
print(Z/sum(Z))


# --------->
Z = (Z - np.mean (Z)) / (np.std (Z))
Z

[[-6.48704643  0.15570476 -0.2651725  -0.66009487 -0.02993715]
 [ 2.44515505 -6.13622616  1.24204911  1.99713192 -0.3132316 ]
 [-4.29722683  6.40778555  0.92611318  1.8838901   0.45850273]
 [ 6.88813463 -0.7820369  -2.24173389  0.02380043  0.83237176]
 [ 2.45098358  1.35477275  1.3387441  -2.24472758  0.05229425]]


array([[ 1.88596252, -0.12359389, -0.21698572, -0.5018211 , -0.1373509 ],
       [-0.83273708,  1.29437644,  0.51329668,  1.16199723, -0.59959025],
       [ 1.2194458 , -1.53258345,  0.36021869,  1.09109105,  0.65961541],
       [-2.18504947,  0.08773867, -1.17467369, -0.07360115,  1.26964139],
       [-0.83451111, -0.39381981,  0.56014756, -1.49403635, -0.00317747]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [123]:
np.array([1], dtype='int32')

array([1])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [88]:
m1 = np.random.randn(5,3)
m2 = np.random.randn(3,2)
#m1.mat(m2)
print(np.matmul(m1, m2))

#------------>

Z = np.dot(m1, m2)
print(Z)


[[-0.57355307 -1.43091249]
 [ 0.23585284 -1.12765414]
 [ 1.77421375  4.86012783]
 [-0.76538597 -1.57587478]
 [-0.71953505 -4.89391272]]
[[-0.57355307 -1.43091249]
 [ 0.23585284 -1.12765414]
 [ 1.77421375  4.86012783]
 [-0.76538597 -1.57587478]
 [-0.71953505 -4.89391272]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [90]:
Z = np.arange(10)
Z[2:9] = Z[2:9] * -1
print(Z)

#--------->
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1 -2 -3 -4 -5 -6 -7 -8  9]
[ 0  1 -2 -3 -4 -5 -6 -7 -8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [139]:
#print(np.sum((range(5), -1)))

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [77]:
print(Z**Z)
print(Z <- Z)
print(Z/1/1)
1j*Z

[[       nan        nan 2.57544419        nan 0.82889336 0.84587756
  0.70556519 0.852227   0.98175794 0.8932999 ]
 [0.76342615 2.22849409        nan 0.72809447        nan        nan
  0.72497672 1.10901967        nan 2.56196664]
 [       nan 1.16111594        nan        nan        nan 0.82928313
         nan        nan 0.69306892        nan]
 [       nan        nan        nan        nan        nan 2.5724509
         nan 3.29612355 0.85355013 1.25626828]
 [       nan 0.69269634 0.86844088        nan        nan        nan
  1.02366334 1.02264028        nan 0.75088499]
 [       nan 1.2532519  1.04109111 0.70927113        nan 0.78089806
         nan 0.71955407        nan 1.41931317]
 [1.63899552        nan        nan        nan        nan        nan
  2.01071038 0.69250503 1.39351556        nan]
 [0.76625955 2.06028147 1.11528691        nan 0.74451908        nan
         nan        nan        nan        nan]
 [4.8930582  0.75940596        nan 0.73178547        nan 1.54840066
  0.71685052 

array([[-0.-0.39898318j, -0.-0.14264254j,  0.+1.72856044j,
        -0.-0.32063479j,  0.+0.07091701j,  0.+0.05921757j,
         0.+0.49271354j,  0.+0.82351803j,  0.+0.98141574j,
         0.+0.87961057j],
       [ 0.+0.13460558j,  0.+1.63331676j, -0.-0.16744507j,
         0.+0.57694518j, -0.-0.38188599j, -0.-0.95014994j,
         0.+0.19955475j,  0.+1.09875336j, -0.-1.1620012j ,
         0.+1.7251673j ],
       [-0.-0.92887008j,  0.+1.14000826j, -0.-0.40546866j,
        -0.-1.21399405j, -0.-1.39310154j,  0.+0.78872554j,
        -0.-1.28796264j, -0.-0.49173327j,  0.+0.39866477j,
        -0.-0.07006662j],
       [-0.-0.39276719j, -0.-0.85056921j, -0.-0.42632513j,
        -0.-0.21480862j, -0.-1.77871328j,  0.+1.72780875j,
        -0.-0.07458203j,  0.+1.88364906j,  0.+0.82544041j,
         0.+1.20789452j],
       [-0.-1.26459541j,  0.+0.39106724j,  0.+0.84651115j,
        -0.-1.68054505j, -0.-0.06234953j, -0.-2.09321906j,
         0.+1.02312242j,  0.+1.02214439j, -0.-1.53089376j,
         0.

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [143]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))



nan
0
[-2.14748365e+09]


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [38]:
Z = np.zeros(4)
A = np.arange(4)
print(A, Z)

Z == A

[0 1 2 3] [0. 0. 0. 0.]


array([ True, False, False, False])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [81]:
np.sqrt(-1) == np.emath.sqrt(-1)

np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [41]:
A = np.array((2,2))
B = np.array((2,2))
(A+B)*(-A/2)

array([-4., -4.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [45]:
np.random.rand(10)

array([0.36055203, 0.78423118, 0.13956528, 0.85498108, 0.30140158,
       0.88429377, 0.80292093, 0.04344034, 0.92808622, 0.32323034])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [56]:
Z = np.random.randint(0, 4, (5,5))
Z

array([[0, 3, 3, 1, 1],
       [3, 1, 3, 0, 1],
       [3, 2, 1, 2, 1],
       [0, 1, 1, 3, 0],
       [3, 2, 1, 1, 1]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [57]:
Z = np.random.random_sample(10)


array([0.57359249, 0.77965739, 0.00982222, 0.84863709, 0.61522063,
       0.15622728, 0.77201712, 0.03313074, 0.94953233, 0.65907961])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [92]:
Z = np.random.randn(10)
print(np.sort(Z))

# ------->
Z.sort()
print(Z)

[-2.12899037 -1.99736508 -1.16631545 -1.00859969 -0.5601631  -0.46109621
  0.16734875  0.18131872  0.39244215  0.60019416]
[-2.12899037 -1.99736508 -1.16631545 -1.00859969 -0.5601631  -0.46109621
  0.16734875  0.18131872  0.39244215  0.60019416]


#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [103]:
A = np.random.randn(3)
B = np.random.randn(3)
np.any(A==B)

False

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [97]:
Z = np.arange(10)
Z[Z == Z.max()] = 0
print(Z)

#------------>
Z[Z.argmax()] = 0
print(Z)

[0 1 2 3 4 5 6 7 8 0]
[0 1 2 3 4 5 6 7 0 0]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [93]:
Z = np.random.randn(5,5)
Z

array([[ 0.46401246,  1.199054  , -0.10183036, -1.10946629,  1.00572969],
       [-1.144753  ,  0.20082543, -0.06138012, -1.0680823 ,  2.13693402],
       [-0.49243566, -0.76265731,  2.00225646, -1.17552072, -1.26003751],
       [ 1.19859924,  0.26851557, -0.94059357,  1.60675504, -0.27065349],
       [-0.40836343, -0.41697801, -1.03633927, -2.22611992, -1.90550172]])

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [100]:
Z = np.random.rand(2,2)
print(Z[:,0] == np.nan)

print((~Z.any(axis=0)).any())


[]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
Class Array:
    def __init__(self, name):
        self.name = name


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [67]:
I = [ 0,3,5,6]
X = np.arange(10)


array([0, 3, 5, 6])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [13]:
Z = np.array([1,2,3,4,5])
A = np.zeros(17)
A[::4] = np.arange(1,6)
Z, A

(array([1, 2, 3, 4, 5]),
 array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.]))

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

In [19]:
Z = np.random.rand(3, 3)
print(Z)
temp = Z[0]
Z[0] = Z[2]
Z[2] = temp
Z 

[[0.25260436 0.19567054 0.2441429 ]
 [0.64084567 0.26338918 0.10782886]
 [0.27526198 0.10964327 0.88905101]]


array([[0.27526198, 0.10964327, 0.88905101],
       [0.64084567, 0.26338918, 0.10782886],
       [0.27526198, 0.10964327, 0.88905101]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [39]:
Z = np.arange(1, 15)
print(Z)
Z[:4:-1]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([14, 13, 12, 11, 10,  9,  8,  7,  6])

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)